chrome.system.cpu.getInfo(function(info){
    console.log('cpu:',info);
});
chrome.system.memory.getInfo(function(info){
    console.log('memory:',info);
});
chrome.system.storage.getInfo(function(info){
    console.log('storage:',info);
});
